version: '3'

services:
  sac-api:
    build:
      context: .
      dockerfile: dockerFiles/web.dockerfile

    ports:
        - 5000:80
    
    volumes:
      - ./src:/var/www/html
    
    depends_on:
      - sac-db
  
    environment:
      - ConnectionString=Server=sac-db;Port=3306;Database=sac_web_api;Uid=sac_web_api_ufjf;Pwd=s@cw3b4p1;
  sac-db:
    image: mysql:5.7

    volumes:
      - ./database:/var/lib/mysql
      - ./db-import.sql:/docker-entrypoint-initdb.d/dump.sql
    
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sac_web_api
      MYSQL_USER: sac_web_api_ufjf
      MYSQL_PASSWORD: s@cw3b4p1
